# Generated by Django 5.2.8 on 2025-11-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_alter_categoriamaterial_name_alter_material_name'),
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Material de la receta',
                'verbose_name_plural': 'Materiales de recetas',
            },
        ),
    ]
