# Generated by Django 5.2.8 on 2025-11-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_alter_categoriamaterial_name_alter_material_name'),
        ('recetas', '0002_materialreceta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='materiales',
            field=models.ManyToManyField(through='recetas.MaterialReceta', to='materiales.material'),
        ),
    ]
