# Generated by Django 5.2.8 on 2025-11-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_receta_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreceta',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
