# Generated by Django 5.2.8 on 2025-11-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_materialreceta_price_total'),
        ('variedadFlor', '0006_alter_typevariedadflor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariedadFlorReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variedadFlor.variedadflor')),
            ],
        ),
    ]
