# Generated by Django 5.2.8 on 2025-11-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_variedadflorreceta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variedadflorreceta',
            old_name='quantity',
            new_name='quantity_bouquets',
        ),
        migrations.AddField(
            model_name='variedadflorreceta',
            name='quantity_stems',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
