# Generated by Django 5.2.8 on 2025-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_rename_quantity_variedadflorreceta_quantity_bouquets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='total_materiales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='materialreceta',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
