# Generated by Django 5.2.8 on 2025-11-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_receta_total_materiales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='description',
        ),
    ]
