# Generated by Django 5.2.8 on 2025-11-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_remove_receta_description'),
        ('variedadFlor', '0006_alter_typevariedadflor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variedadflorreceta',
            old_name='price_total',
            new_name='price_total_tallos',
        ),
        migrations.AddField(
            model_name='receta',
            name='total_variedades',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='variedades',
            field=models.ManyToManyField(through='recetas.VariedadFlorReceta', to='variedadFlor.variedadflor'),
        ),
    ]
