# Generated by Django 5.2.8 on 2025-11-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0009_rename_price_total_variedadflorreceta_price_total_tallos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variedadflorreceta',
            name='price_total_tallos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
