# Generated by Django 5.2.8 on 2025-11-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0010_alter_variedadflorreceta_price_total_tallos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialreceta',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='total_variedades',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='variedadflorreceta',
            name='price_total_tallos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
