# Generated by Django 5.2.8 on 2025-12-01 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoDeObra', '0004_manodeobra_variedad_costo_tinturar'),
        ('recetas', '0011_alter_materialreceta_price_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='total_mano_de_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.CreateModel(
            name='ManoDeObraReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('mano_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manoDeObra.manodeobra')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='manos_de_obra',
            field=models.ManyToManyField(through='recetas.ManoDeObraReceta', to='manoDeObra.manodeobra'),
        ),
    ]
