# Generated by Django 5.2.8 on 2025-12-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0012_receta_total_mano_de_obra_manodeobrareceta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variedadflorreceta',
            old_name='quantity_bouquets',
            new_name='quantity_stems_of_variety',
        ),
        migrations.RemoveField(
            model_name='variedadflorreceta',
            name='quantity_stems',
        ),
        migrations.AddField(
            model_name='receta',
            name='quantity_bouquets',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='quantity_stems_for_bouquets',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
