# Generated by Django 5.2.8 on 2025-12-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0013_rename_quantity_bouquets_variedadflorreceta_quantity_stems_of_variety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variedadflorreceta',
            name='style_stems',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
