# Generated by Django 5.2.8 on 2025-11-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VariedadFlor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type_flor', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Variedad de flor',
                'verbose_name_plural': 'Variedades de flores',
            },
        ),
    ]
