# Generated by Django 5.2.8 on 2025-11-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variedadFlor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variedadflor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
