# Generated by Django 5.2.8 on 2025-11-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variedadFlor', '0002_alter_variedadflor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variedadflor',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
