# Generated by Django 5.2.8 on 2025-11-21 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variedadFlor', '0003_alter_variedadflor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeVariedadFlor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='variedadflor',
            name='type_flor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variedadFlor.typevariedadflor'),
        ),
    ]
