# Generated by Django 5.2.8 on 2025-11-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variedadFlor', '0004_typevariedadflor_alter_variedadflor_type_flor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typevariedadflor',
            options={'verbose_name': 'Tipo de variedad de flor', 'verbose_name_plural': 'Tipos de variedades de flores'},
        ),
    ]
