# Generated by Django 5.2.8 on 2025-11-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variedadFlor', '0005_alter_typevariedadflor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typevariedadflor',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
