# Generated by Django 5.2.8 on 2025-11-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoDeObra', '0002_alter_manodeobra_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manodeobra',
            name='cost_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
