# Generated by Django 5.2.8 on 2025-12-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoDeObra', '0003_alter_manodeobra_cost_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='manodeobra',
            name='variedad_costo_tinturar',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
