# Generated by Django 5.2.8 on 2025-12-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manoDeObra', '0004_manodeobra_variedad_costo_tinturar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manodeobra',
            old_name='variedad_costo_tinturar',
            new_name='variedades_costo_tinturar',
        ),
    ]
