# Generated by Django 5.2.8 on 2025-12-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoDeObra', '0005_rename_variedad_costo_tinturar_manodeobra_variedades_costo_tinturar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoVariedadTinturar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_variedad', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Costo de variedad a tinturar',
                'verbose_name_plural': 'Costo de variedades a tinturar',
            },
        ),
        migrations.RemoveField(
            model_name='manodeobra',
            name='variedades_costo_tinturar',
        ),
    ]
