# Generated by Django 5.2.8 on 2025-12-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_alter_categoriamaterial_name_alter_material_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='price',
            new_name='cost_hour',
        ),
    ]
