# Generated by Django 5.2.8 on 2025-12-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_rename_price_material_cost_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='cost_hour',
            new_name='price',
        ),
    ]
